In [1]:
from dados_api import previsao_temperatura

In [2]:
df1, df2 = previsao_temperatura (-23.544031557296496, -46.63887188820417)

Coordinates: -23.514938354492188°N -46.610504150390625°E
Elevation: 755.0 m asl
Timezone difference to GMT+0: 0s

Hourly data
                          date  temperature_2m
0   2026-10-21 00:00:00+00:00       15.000000
1   2026-10-21 01:00:00+00:00       14.500000
2   2026-10-21 02:00:00+00:00       14.050000
3   2026-10-21 03:00:00+00:00       13.600000
4   2026-10-21 04:00:00+00:00       13.800000
..                        ...             ...
163 2026-10-27 19:00:00+00:00       17.450001
164 2026-10-27 20:00:00+00:00       17.150000
165 2026-10-27 21:00:00+00:00       16.799999
166 2026-10-27 22:00:00+00:00       16.400000
167 2026-10-27 23:00:00+00:00       16.049999

[168 rows x 2 columns]

In [3]:
df1

                         date  temperature_2m  dia  mes    dia_semana
0   2026-10-21 00:00:00+00:00       15.000000   21   10  Quarta-feira
1   2026-10-21 01:00:00+00:00       14.500000   21   10  Quarta-feira
2   2026-10-21 02:00:00+00:00       14.050000   21   10  Quarta-feira
3   2026-10-21 03:00:00+00:00       13.600000   21   10  Quarta-feira
4   2026-10-21 04:00:00+00:00       13.800000   21   10  Quarta-feira
..                        ...             ...  ...  ...           ...
163 2026-10-27 19:00:00+00:00       17.450001   27   10   Terça-feira
164 2026-10-27 20:00:00+00:00       17.150000   27   10   Terça-feira
165 2026-10-27 21:00:00+00:00       16.799999   27   10   Terça-feira
166 2026-10-27 22:00:00+00:00       16.400000   27   10   Terça-feira
167 2026-10-27 23:00:00+00:00       16.049999   27   10   Terça-feira

[168 rows x 5 columns]

In [4]:
df2

   dia  mes     dia_semana  temperatura_media
0   21   10   Quarta-feira          17.824999
1   22   10   Quinta-feira          19.106249
2   23   10    Sexta-feira          19.345833
3   24   10         Sábado          21.591667
4   25   10        Domingo          20.341667
5   26   10  Segunda-feira          18.056250
6   27   10    Terça-feira          15.987500